packages:
  - "labs/*"
  - "apps/*"
  - "packages/ai/*"
  - "packages/config/*"
  - "packages/infra/*"
  - "packages/entity/*"
  - "packages/ui/*"
  - "packages/feature/*"
  - "packages/resource/*"
  - "packages/service/*"
