packages:
  - "labs/*"
  - "apps/web"
  - "apps/api"
  - "apps/brochure"
  - "packages/ai/*"
  - "packages/config/*"
  - "packages/infra/*"
  - "packages/entity/*"
  - "packages/ui/*"
  - "packages/feature/*"

