packages:
  - "labs/board"
  - "apps/web"
  - "apps/api"
  - "packages/ai/llamaindex"
  - "packages/config/tailwind-config"
  - "packages/config/eslint-config"
  - "packages/config/typescript-config*"
  - "packages/feature/quill"
  - "packages/feature/three"
  - "packages/infra/drizzle"
  - "packages/infra/trpc"
  - "packages/ui/custom"
  - "packages/ui/shadcn"
  - "packages/ui/content"
