/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 cosmetic.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cosmetic(props) {
  const { nodes, materials } = useGLTF('/glb/cosmetic.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_10.geometry} material={materials['default']} position={[-0.002, 0.12, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/glb/cosmetic.glb')
