import type { Metadata } from "next";
import "./globals.css";
import MaxWidthWrapper from "@ui/shadcn/base/MaxWidthWrapper"
import { Noto_Sans, Nanum_Gothic } from 'next/font/google'
const noto = Noto_Sans({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-noto',
    weight: '400',
})
const nanum = Nanum_Gothic({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-nanum',
    weight: ['400', '700'],
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={' antialiased min-h-screen  '}
            >
                <MaxWidthWrapper>
						{children}
                </MaxWidthWrapper>
            </body>
        </html>
    );
}
